name: Generate and Commit Slideshow Video

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip & Uninstall Conflicting Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip uninstall -y moviepy imageio imageio-ffmpeg numpy decorator tqdm pillow

      - name: Install Stable Versions (Fix for ANTIALIAS)
        run: |
          python -m pip install --no-cache-dir --force-reinstall moviepy==1.0.3 requests imageio[ffmpeg] numpy decorator tqdm pillow==9.4.0

      - name: Debug Installed Versions
        run: |
          python -m pip list
          python -c "import PIL; print(PIL.__version__)"
          python -c "import moviepy.editor; print('✅ MoviePy is installed correctly!')"

      - name: Run slideshow script
        run: python slideshow.py

      - name: Commit and push generated slideshow
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-generated slideshow video"
          git push
        continue-on-error: true
