name: Generate and Commit Slideshow Video

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip & Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir --upgrade moviepy requests imageio[ffmpeg] numpy decorator tqdm

      - name: Debug Installed Packages
        run: python -m pip list  # Ensures MoviePy is installed in the correct Python

      - name: Force Correct Python Path
        run: |
          echo "Python version: $(python --version)"
          echo "Python path: $(which python)"
          python -c "import sys; print(sys.path)"
          python -c "import moviepy.editor; print('✅ MoviePy is installed successfully!')"

      - name: Run slideshow script
        run: python slideshow.py

      - name: Commit and push generated slideshow
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add slideshow.mp4
          git commit -m "Auto-generated slideshow video"
          git push
        continue-on-error: true
