name: Generate and Commit Slideshow Video

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ImageMagick (Fix for TextClip)
        run: |
          sudo apt update
          sudo apt install -y imagemagick

      - name: Fix ImageMagick Security Policy
        run: |
          sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF"/<policy domain="coder" rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@"/<policy domain="path" rights="read|write" pattern="@"/g' /etc/ImageMagick-6/policy.xml

      - name: Upgrade pip & Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir --force-reinstall moviepy requests imageio[ffmpeg] numpy decorator tqdm pillow==9.4.0

      - name: Run slideshow script
        run: python slideshow.py

      - name: Commit and push generated slideshow
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add slideshow.mp4
          git commit -m "Auto-generated slideshow video"
          git push
        continue-on-error: true
